const PAGE_STATES = {
    LOADING_ALL_PLAYLIST: 'LOADING_ALL_PLAYLIST',
    DISPLAY_ALL_PLAYLISTS: 'DISPLAY_ALL_PLAYLISTS',
    SHUFFLING_PLAYLIST: 'SHUFFLING_PLAYLIST',
    DISPLAY_SHUFFLE_RESPONSE: 'DISPLAY_SHUFFLE_RESPONSE'
  };

export default PAGE_STATES;
